# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift


use_frameworks!

inhibit_all_warnings!

target 'Demo' do

# Action library
pod 'Action', :path => '../'

end

target 'DemoTests' do

# Dependencies
pod 'RxSwift', '~> 2.1'
pod 'RxCocoa', '~> 2.1'
pod 'RxBlocking', '~> 2.1'

# Testing libraries
pod 'Quick'
pod 'Nimble'

end

