# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Action library
  pod 'Action', :path => '../'

  target 'DemoTests' do
    inherit! :search_paths

    # Dependencies
    pod 'Action', :path => '../'
    pod 'RxSwift', '~> 2.6'
    pod 'RxCocoa', '~> 2.6'
    pod 'RxBlocking', '~> 2.6'

    # Testing libraries
    pod 'Quick'
    pod 'Nimble'
  end

end
